version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: access-control-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - access-control-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  mongo:
    image: mongo:4
    container_name: mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: ${MONGO_HOST}
      SPRING_DATA_MONGODB_PORT: ${MONGO_PORT}
      SPRING_DATA_MONGODB_USERNAME: ${MONGO_USER}
      SPRING_DATA_MONGODB_PASSWORD: ${MONGO_USER}
      SPRING_DATA_MONGODB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    container_name: backend-service
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  access-control-pgdata:
  rabbitmq-data:
  mongo-data: