spring:

  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DB:test_db}
    username: ${MONGO_USER:mongo_test}
    password: ${MONGO_PASSWORD:mongo_test}
    authentication-database: ${MONGO_AUTHENTICATION:admin}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:test_db}
    username: ${POSTGRES_USER:postgres_test}
    password: ${POSTGRES_PASSWORD:postgres_test}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    routing-key: ${RABBITMQ_ROUTING_KEY:test.queue}
    ssl:
      enabled: false