spring:
  application:
    name: access-control-system

  profiles:
    active: ${ENVIRONMENT}

  flyway:
    enabled: true

jwt:
  public:
    key: classpath:authz.pub
  private:
    key: classpath:authz.pem

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html