spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mongodb:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_DB}
    username: ${MONGO_USER}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGO_AUTHENTICATION}

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    routing-key: ${RABBITMQ_ROUTING_KEY}
    ssl:
      enabled: false