spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:test_db}
    username: ${POSTGRES_USER:postgres_test}
    password: ${POSTGRES_PASSWORD:postgres_test}

  mongodb:
    database: ${MONGO_DB:test_db}

  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:test.exchange}
    # File Received to OCR
    ocr-routing-key: ${RABBITMQ_OCR_ROUTING_KEY:test.ocr.routing}
    ocr-queue: ${RABBITMQ_OCR_QUEUE:test.ocr.queue}
    # File OCR Status
    ocr-status-routing-key: ${RABBITMQ_OCR_STATUS_ROUTING_KEY:test.ocrstatus.routing}
    ocr-status-queue: ${RABBITMQ_OCR_STATUS_QUEUE:test.ocrstatus.queue}
    # File AI validation
    ai-validation-routing-key: ${RABBITMQ_AI_VALIDATION_ROUTING_KEY:test.aivalidation.routing}
    ai-validation-queue: ${RABBITMQ_AI_VALIDATION_QUEUE:test.aivalidation.queue}