spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mongodb:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_DB}
    username: ${MONGO_USER}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGO_AUTHENTICATION}

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    exchange: ${RABBITMQ_EXCHANGE}
    queue: ${RABBITMQ_QUEUE}
    routing-key: ${RABBITMQ_ROUTING_KEY}
    dead-exchange: ${RABBITMQ_DEAD_EXCHANGE}
    dead-queue: ${RABBITMQ_DEAD_QUEUE}
    dead-routing-key: ${RABBITMQ_DEAD_ROUTING_KEY}
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        prefetch: 1
    publisher-confirm-type: correlated
    publisher-returns: true
    ssl:
      enabled: false