spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mongodb:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_DB}
    username: ${MONGO_USER}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGO_AUTHENTICATION}

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    exchange: ${RABBITMQ_EXCHANGE}
    # File Received to OCR
    ocr-routing-key: ${RABBITMQ_OCR_ROUTING_KEY}
    ocr-queue: ${RABBITMQ_OCR_QUEUE}
    # File OCR Status
    ocr-status-routing-key: ${RABBITMQ_OCR_STATUS_ROUTING_KEY}
    ocr-status-queue: ${RABBITMQ_OCR_STATUS_QUEUE}
    # File AI validation
    ai-validation-routing-key: ${RABBITMQ_AI_VALIDATION_ROUTING_KEY}
    ai-validation-queue: ${RABBITMQ_AI_VALIDATION_QUEUE}
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        prefetch: 1
    publisher-confirm-type: correlated
    publisher-returns: true
    ssl:
      enabled: false