spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:test_db}
    username: ${POSTGRES_USER:postgres_test}
    password: ${POSTGRES_PASSWORD:postgres_test}

  mongodb:
    database: ${MONGO_DB:test_db}

  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:test.exchange}
    queue: ${RABBITMQ_QUEUE:test.queue}
    routing-key: ${RABBITMQ_ROUTING_KEY:test.routing}
    dead-exchange: ${RABBITMQ_DEAD_EXCHANGE:test.dead.exchange}
    dead-queue: ${RABBITMQ_DEAD_QUEUE:test.dead.queue}
    dead-routing-key: ${RABBITMQ_DEAD_ROUTING_KEY:test.dead.routing}