name: Backend Service CI/CD

# Only Pull Request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
    paths:
      - "backend-service/**"

jobs:

  # JOB 1 - BUILD + TEST + COVERAGE
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Set env vars
        run: |
          echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV

      - name: Compile project
        run: mvn clean compile

      - name: Inject JWT keys
        run: |
          mkdir -p target/classes
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > target/classes/authz.pem
          echo "${{ secrets.JWT_PUBLIC_KEY }}" > target/classes/authz.pub

      - name: Run tests + coverage
        run: mvn verify

  # JOB 2 - SONARCLOUD
  sonar:
    runs-on: ubuntu-latest
    needs: build-test

    defaults:
      run:
        working-directory: backend-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.coverage.jacoco.xmlReportPaths=backend-service/target/site/jacoco/jacoco.xml

  # JOB 3 - SECURITY
  security:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build project
        run: cd backend-service && mvn clean compile

      - name: Analyze security
        uses: github/codeql-action/analyze@v3